name: Test Validate Access JS Action

on:
  workflow_dispatch:

jobs:
  validate-access:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Validate Access JS Action
        uses: action.yaml
